version: '3'
services:
  nestjs:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - '3000:3000'
    env_file:
      - .env.local
    volumes:
      - ./:/usr/local/apps/myapp
      - /usr/local/apps/myapp/node_modules